"""Evaluate focus detection against labeled ground truth.

Reads labels.csv and one or more metrics CSV files generated by replay_video.py.
Computes accuracy, precision, recall, and state switch frequency.

Usage:
  python focus_lab/evaluate.py focus_lab/data/labels.csv focus_lab/outputs/

Labels CSV format:
  video,start_ms,end_ms,label
  screen_01.avi,0,30000,focused
  writing_01.avi,0,30000,focused
  turn_left_01.avi,3000,9000,distracted
  away_01.avi,5000,20000,away
"""
import csv
import os
import sys
from collections import defaultdict


def load_labels(labels_csv: str) -> list[dict]:
    rows = []
    with open(labels_csv, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            row["start_ms"] = int(row["start_ms"])
            row["end_ms"] = int(row["end_ms"])
            rows.append(row)
    return rows


def load_metrics(metrics_csv: str) -> list[dict]:
    rows = []
    with open(metrics_csv, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            row["timestamp_ms"] = int(row["timestamp_ms"])
            row["score"] = float(row["score"])
            row["presence"] = row["presence"].lower() in ("true", "1", "yes")
            rows.append(row)
    return rows


def evaluate_one(labels: list[dict], metrics: list[dict], video_name: str) -> dict:
    """Match metrics timestamps against label segments for one video."""
    # Filter labels for this video
    video_labels = [lbl for lbl in labels if video_name in lbl["video"]]
    if not video_labels:
        return {"error": f"No labels found for video '{video_name}'"}

    # For each metric row, find which label it falls into
    label_for_row = []
    for row in metrics:
        ts = row["timestamp_ms"]
        matched = None
        for lbl in video_labels:
            if lbl["start_ms"] <= ts <= lbl["end_ms"]:
                matched = lbl["label"]
                break
        label_for_row.append((row, matched))

    if not label_for_row:
        return {"error": "No metrics matched"}
    matched_rows = [(r, l) for r, l in label_for_row if l is not None]
    if not matched_rows:
        return {"error": "No metrics matched any label segment", "total_rows": len(label_for_row)}

    # Accuracy
    correct = sum(1 for _, lbl in matched_rows if _["status"] == lbl)
    acc = correct / len(matched_rows) if matched_rows else 0

    # Per-class precision/recall
    classes = set(l for _, l in matched_rows) | set(r["status"] for r, _ in matched_rows)
    per_class = {}
    for c in classes:
        tp = sum(1 for r, l in matched_rows if r["status"] == c and l == c)
        fp = sum(1 for r, l in matched_rows if r["status"] == c and l != c)
        fn = sum(1 for r, l in matched_rows if r["status"] != c and l == c)
        prec = tp / (tp + fp) if (tp + fp) > 0 else 0
        rec  = tp / (tp + fn) if (tp + fn) > 0 else 0
        per_class[c] = {"precision": round(prec, 4), "recall": round(rec, 4)}

    # State switch count
    switches = sum(1 for i in range(1, len(matched_rows))
                   if matched_rows[i][0]["status"] != matched_rows[i - 1][0]["status"])
    switch_rate_per_min = switches / (len(matched_rows) / 15.0) if matched_rows else 0  # assuming ~15fps

    # Detection delay: time from label start to correct prediction
    delays = []
    current_label = None
    delay_start = 0
    for row, lbl in label_for_row:
        if lbl != current_label:
            current_label = lbl
            delay_start = row["timestamp_ms"]
        if lbl and row["status"] == lbl:
            delays.append(row["timestamp_ms"] - delay_start)

    import statistics
    avg_delay = statistics.mean(delays) if delays else 0

    return {
        "video": video_name,
        "matched_frames": len(matched_rows),
        "total_frames": len(metrics),
        "accuracy": round(acc, 4),
        "per_class": per_class,
        "state_switches": switches,
        "switch_rate_per_min": round(switch_rate_per_min, 1),
        "avg_detection_delay_ms": round(avg_delay, 0),
    }


def find_metric_files(outputs_dir: str) -> dict[str, str]:
    """Find all metrics CSV files, keyed by approximate video name."""
    result = {}
    for fname in os.listdir(outputs_dir):
        if fname.endswith("_metrics.csv"):
            key = fname.replace("_metrics.csv", "")
            result[key] = os.path.join(outputs_dir, fname)
    return result


def main():
    if len(sys.argv) < 3:
        print("Usage: python focus_lab/evaluate.py <labels.csv> <outputs_dir>")
        print("  labels.csv: ground-truth label file")
        print("  outputs_dir: directory containing *_metrics.csv from replay_video.py")
        sys.exit(1)

    labels_csv = sys.argv[1]
    outputs_dir = sys.argv[2]

    if not os.path.isfile(labels_csv):
        print(f"Error: labels file not found: {labels_csv}")
        sys.exit(1)

    labels = load_labels(labels_csv)
    metric_files = find_metric_files(outputs_dir)

    if not metric_files:
        print(f"Error: no *_metrics.csv files found in {outputs_dir}")
        print("Generate them with: python focus_lab/replay_video.py <video> --csv <out> --no-show")
        sys.exit(1)

    print(f"Labels: {labels_csv} ({len(labels)} segments)")
    print(f"Metrics: {len(metric_files)} files in {outputs_dir}")
    print()

    all_results = []
    all_switches = 0
    all_correct = 0
    all_total = 0
    per_class_agg: dict[str, dict[str, float]] = defaultdict(lambda: {"tp": 0, "fp": 0, "fn": 0})

    for key, mf in sorted(metric_files.items()):
        metrics = load_metrics(mf)
        res = evaluate_one(labels, metrics, key)
        if "error" in res:
            print(f"  {key}: ERROR - {res['error']}")
            continue

        all_correct += sum(1 for i in range(res["matched_frames"])
                           if metrics[i]["status"] == "focused")  # simplified, full matching in evaluate_one
        all_total += res["matched_frames"]
        all_switches += res["state_switches"]

        for cls, vals in res["per_class"].items():
            # simplified aggregation — just report per-video for now
            pass

        all_results.append(res)

        print(f"  {res['video']}: "
              f"acc={res['accuracy']:.3f}  "
              f"frames={res['matched_frames']}  "
              f"switches={res['state_switches']} ({res['switch_rate_per_min']}/min)  "
              f"delay={res['avg_detection_delay_ms']:.0f}ms")
        for cls, vals in res["per_class"].items():
            print(f"    {cls:<13} prec={vals['precision']:.3f}  rec={vals['recall']:.3f}")

    if all_results:
        avg_acc = sum(r["accuracy"] for r in all_results) / len(all_results)
        print(f"\n{'=' * 50}")
        print(f"Summary: {len(all_results)} videos")
        print(f"  Average accuracy: {avg_acc:.3f}")
        print(f"  Total switches:   {all_switches}")
        print(f"{'=' * 50}")


if __name__ == "__main__":
    main()
